### ISSUE TITLE
Vignette Output Differences 

### ISSUE THREAD

**Issue by korydjohnson** [bkeller2/mlmpower#4]
Hi,

I would very much like you use this package for power calculations, but the output I generate from the vignette code is different from that shown in the vignette. 

Most importantly, the row for "Random: Slopes Test" is missing entirely.

Secondly, summary(powersim1) includes the statement:

── lme4 Model Syntax 

y ~ 1 + NA + NA + NA:cgm(z1) + NA:cgm(z2) + NA:cgm(z1) + NA:cgm(z2) + cgm(z1) + cgm(z2) + (1 + NA + NA | `_id`)

Lastly, calculations for the remainder of the tables qualitatively match, but not numerically (even after setting the seed).

── Power Analysis Results ──

── global icc = 0.1, n_within = 10, n_between = 30 
                        Power      
Fixed:  (Intercept)     1.00 ± 0.00
Fixed:  cwc(x1)         0.94 ± 0.01
Fixed:  cgm(x2)         0.23 ± 0.02
Fixed:  cgm(z1)         0.92 ± 0.01
Fixed:  cgm(z2)         0.15 ± 0.02
Fixed:  cwc(x1):cgm(z1) 0.29 ± 0.02

I am running "R version 4.3.2 (2023-10-31)" and package version mlmpower_1.0.4.

Best,

Kory

**Comment by bkeller2** [comment]
@korydjohnson 

Can you please provide the exact code you ran to obtain this output?

Thanks!

**Comment by korydjohnson** [comment]
Thanks for the quick reply! Code below. Note that in this run I didn't want to wait for the full set of 16 simulation scenarios, so chose fixed values for n_between and n_within (possible cause of numerical differences, though it appears to be the first case run either way).

```
library(mlmpower)
example1 <- (
    effect_size(
        icc          = c(.10, .25),
        within       = .065,
        between      = .065,
        product      = .01,
        random_slope = .03
    )
    + outcome('y', mean = 50, sd = 10)
    + within_predictor('x1', icc = 0, weight = .80)
    + within_predictor('x2', weight = .20)
    + between_predictor('z1', weight = .80)
    + between_predictor('z2', weight = .20)
    + product('x1','z1', weight = 1)
    + random_slope('x1', weight = 1)
    + correlations(
        within  = random(0.1, 0.3),
        between = random(0.1, 0.3),
        randeff = random(0.1, 0.3)
    )
)

# Set seed for replicable results
set.seed(2318971)

# Run Power Analysis
powersim1 <-
    power_analysis(
        model = example1,
        replications = 2000,
        n_between = c(30),
        n_within = c(10)
    )
powersim1
```

**Comment by bkeller2** [comment]
@korydjohnson 

Thank you for reaching out; I have fixed two issues:
- a321cd9 has fixed the issue with `NA` in the printed formula.
- 4ab513b has fixed the issue with no likelihood ratio tests being conducted

To your other question, the results from the vignette are based on an older version of R and the package. Because these simulations take a while, they cannot be directly run when building the vignette (i.e., the [vignette folder](https://github.com/bkeller2/mlmpower/tree/main/vignettes) has the precompiled results saved as rds files) and I do not always update the precompiled results with a new version. I will update these precompiled results, but running it all will take half a day or so. 

Once that is done, I will submit a new version to CRAN (which will take a day or so to update). Until then, you can use the two fixes by installing the package via GitHub:

```r
remotes::install_github('bkeller2/mlmpower', build_vignettes = TRUE)
```

Thanks again!

**Comment by korydjohnson** [comment]
@bkeller2: works great; thanks for the quick updates!

**Comment by bkeller2** [comment]
@korydjohnson 

Great! 1.0.5 is now being populated on CRAN as well. Thanks again for finding this!
