### ISSUE TITLE
Feature request: unequal cluster sizes

### ISSUE THREAD

**Issue by mkshaw** [bkeller2/mlmpower#7]
Hi Brian,

Thanks again for your work on this package! I'm using the `generate()` function to simulate data for a non-power-related simulation study, and to make the data a bit more "believable," I'm interested in generating clusters with unequal sample sizes. Something like if you have 1...J clusters with average sample size n, you divide the clusters into three groups where the first group of clusters has sample size 3n/5 observations, the second group has sample size n, and the third sample size 7n/5 observations.

So for example, you have 15 clusters and the average sample size is 20. The first 5 clusters have 3n/5 = 12 observations each, the next five clusters have 20 observations each, and the last five clusters have 7n/5 = 28 observations each. Would it be possible for you to integrate a feature like this? I recognize this is beyond the intended scope of the package, so would also be happy just to hear if you have ideas about how to integrate this on my end without compromising the data quality (e.g., I wouldn't just move observations between clusters).

Thank you!

**Comment by bkeller2** [comment]
@mkshaw 

Hey!

This is too specific to add functionality to the package because what you want can be obtained through existing methods. Unequal sample sizes can be conceptualized as a form of missing data. Missing data can be incorporated in the `generate()` function using the `mechanism` input. Here is a quick hard-coded version of what you are requesting for:

```r
# Load package
library(manpower)

# Create Model
model <- (
    outcome('Y')
    + within_predictor('X')
    + effect_size(ICC = 0.1)
)
# Set seed
set.seed(198723)


# Induce unequal sample size
# Set `n_within` to max sample size
model |> generate(n_within = 28, n_between = 15, mechanism = \(data) {
    # `data` will be the `mp_data` used
    for (i in 1:5) {
        data[data$`_id` == i, -1][13:28,] <- NA
    }
    for (i in 6:10) {
        data[data$`_id` == i, -1][21:28,] <- NA
    }
    # Return data
    data  |> na.omit() # Drop missing
}) -> unequal_sample
```

The `mechanism` input takes a function with one input, the data set, and should also return that data set. The type of unequal sample size you want would follow a missing at random mechanism because the missing data is due to cluster membership (i.e., 1/3 of the clusters to have 20 observations and 1/3 of the clusters to have 12 observations, 1/3 clusters are complete).

Alternatively, you could induce missing completely at random data by using the `MCAR()` function in `mlmpower`. For example, setting `n_between = 40` with `MCAR(0.5)` would give you a 20 sample size on average, but every data set would have small random variations. Then, each cluster would have a random within-cluster sample size, but all would be unequal.

Let me know if this works. If I were to include a feature like this, it would essentially be something similar, inducing missing data, but it would be a pre-created function like the `MCAR()` or `MAR()` functions already in the package.

**Comment by mkshaw** [comment]
Hey! That does work, I implemented both solutions and both seem to play nicely with centering as well, here's an example of what each looks like on my end. Thank you for your help!

```
# load dependency
library(mlmpower)

# example conditions
n = 15
c = 15
ndat = 5
effect = 0.1

# model setup
model <- (
    effect_size(
      icc = 0.25,
      within = effect,
      random_slope = 0.03
    )
    + outcome('y')
    + within_predictor('x1', icc = 0)
    + within_predictor('x2', icc = 0)
    + random_slope('x1')
)

t1_pop <- summary(model)$tau[2,2]
g10_pop <- summary(model)$gammas[2]
g11_pop <- summary(model)$gammas[3]
pop_values <- c(g10_pop, g11_pop, t1_pop)
```

```
# MAR mechanism

smallest_n = (3*n)/5
largest_n = (7*n)/5

dat <- generate(model, n_within = largest_n, n_between = c, mechanism = \(data) {
  for (i in 1:(c/3)) {
    data[data$`_id` == i, -1][smallest_n+1:largest_n, ] <- NA
  }
  for (i in ((c/3)+1):(2*(c/3))) {
    data[data$`_id` == i, -1][n+1:largest_n, ] <- NA
  }
  # return data
  data |> na.omit() # drop missing
}) |> center(x1 = cwc, x2 = cwc)

dat$g10_pop <- g10_pop
dat$g11_pop <- g11_pop
dat$t1_pop <- t1_pop

# peek at data
dat
```

```
# MCAR
dat <- generate(model, n_within = n*2, n_between = c, ndata = ndat, mechanism = MCAR(0.5))
for (i in 1:length(dat)) {
  dat[[i]] <- dat[[i]] |> na.omit()
  dat[[i]]$g10_pop <- g10_pop
  dat[[i]]$g11_pop <- g11_pop
  dat[[i]]$t1_pop <- t1_pop
}
dat <- dat |> center(x1 = cwc, x2 = cwc)

# peek at data
dat 
```
